### ISSUE TITLE
Using with sunmi  print package

### ISSUE THREAD

**Issue by sergiotucano** [brasizza/danfe-package#1]
Hey Marcus, is possible use this package with your sunmi print package?

Thanks!

**Comment by brasizza** [comment]
which package bro ?

**Comment by sergiotucano** [comment]
https://pub.dev/packages/sunmi_printer_plus

**Comment by brasizza** [comment]
Sure it can, when you build the buffer , you can use in the printRaw method with no problem
if you have some issue with that just let me know
