### ISSUE TITLE
Erro de calculo de DESCONTO e SUBTOTAL

### ISSUE THREAD

**Issue by murilorissos** [brasizza/danfe-package#4]
Há um erro no arquivo de model total.dart, ele não está calculando corretamente o desconto e a solução que encontrei foi essa:

      desconto: (map['ICMSTot']['vDesc']),

**Comment by murilorissos** [comment]
algum andamento?

**Comment by brasizza** [comment]
@murilorissos Estava em viagem ja vou analisar e te retorno , tem algum xml de teste? Pode me mandar por e-mail: mvbdesenvolvimento@gmail.com

**Comment by brasizza** [comment]
esse xml é de nfce ? nfe ? sat ? por favor se possível me encaminhe para eu ver onde esta o problema porque o map['ICMSTot']['vDesc'] tem no ternário quando não é sat @murilorissos

**Comment by murilorissos** [comment]
@brasizza enviado um XML de teste.

**Comment by brasizza** [comment]
@murilorissos , issue resolvida
https://pub.dev/packages/danfe

Obrigado pela informação!
