### ISSUE TITLE
Impressão de um XML com CNPJ

### ISSUE THREAD

**Issue by smorigo** [brasizza/danfe-package#7]
Olá, utilizei sua lib e um projeto e reparei que emissões onde são feitas com CNPJ o documento não está sendo impresso:

`...
</emit><dest><CNPJ>63167747000159</CNPJ><xNome>NOME DA EMPRESA LTDA</xNome></dest>
...`

**Comment by brasizza** [comment]
vc pode me enviar o xml para eu analisar ?
@smorigo

**Comment by smorigo** [comment]
Boa tarde Marcus tudo bem ? Vou enviar pra você para que possamos corrigir

**Comment by brasizza** [comment]
me manda por email
mvbdesenvolvimento@gmail.com

@smorigo

**Comment by brasizza** [comment]
Parece que foi corrigido na versao final 0.0.20
