### ISSUE TITLE
qrcode printando apenas o link

### ISSUE THREAD

**Issue by unleed-l** [brasizza/danfe-package#8]
Estou tendo um problema na impressão do qrcode, ao invés de criar o qrcode ele está apenas imprimindo o próprio link do qrcode.
Obs.: Estou utilizando o DanfePrinter.

![nfe1](https://github.com/user-attachments/assets/c38b6a52-7d64-479a-999d-01bb8c0ef9d4)

**Comment by brasizza** [comment]
> Estou tendo um problema na impressão do qrcode, ao invés de criar o qrcode ele está apenas imprimindo o próprio link do qrcode. Obs.: Estou utilizando o DanfePrinter.
> 
> ![nfe1](https://private-user-images.githubusercontent.com/31933158/355965036-c38b6a52-7d64-479a-999d-01bb8c0ef9d4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjA1MzIsIm5iZiI6MTcyMzA2MDIzMiwicGF0aCI6Ii8zMTkzMzE1OC8zNTU5NjUwMzYtYzM4YjZhNTItN2Q2NC00NzlhLTk5OWQtMDFiYjhjMGVmOWQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE5NTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZDI5ZDM0NTcyNjY0MGFlM2E1OGU4ZWRlYWQ2NGVjZGFlNjg3NTI3MTE4ZjMwNzI3MjkwMTgzMDg3YzYxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nDaWmdruWeC9CoDOeb_TVkxzMMCqXINRQrJGCHq0oVc)

Qual modelo da sua impressora? 
ela ta atualizado com o firmware pra imprimir qrcode ?
manda seu xml pra mim no  mvbdesenvolvimento@gmail.com pra eu testar na minha impressora e te da  o feedback!?

**Comment by unleed-l** [comment]
A impressora é a Bematech MP-4200 TH, ela está atualizada. Vou enviar pra ti o xml via e-mail.

**Comment by unleed-l** [comment]
Infelizmente não consegui fazer funcionar com o package, porém, acabei utilizando o package qr_image_generator para gerar a imagem do qrcode e imprimi com o imageRaster do generator. Muito obrigado pelo apoio!

**Comment by brasizza** [comment]
Maravilha, so a fim de curiosidade na minha impressora funcionou a impressão do qrcode então o problema n é no package![image](https://github.com/user-attachments/assets/c47f68af-f6b5-40ce-a0c8-c2aac942cb17)
